AMAC02FT45YMD6M 2021-12-07

diff --git a/kriskindle b/kriskindle
--- a/kriskindle
+++ b/kriskindle
@@ -43,13 +43,21 @@ done
 
 shift $((OPTIND - 1))
 # init switch flags
-run_id="${EPOCHSECONDS}.$RANDOM$RANDOM"
-participants="participants.$run_id"
+
+declare -g run_id run
+
+set_run_id () {
+    run_id="${EPOCHSECONDS}.$RANDOM$RANDOM"
+    run="run.$run_id"
+    all="$run/all"
+    fails="$run/fails"
+}
+
+set_run_id
 exclusions="exclusions"
 assignments="assignments"
 candidates="candidates"
-assigned="$participants/assigned"
-all="$participants/all"
+# assigned="$participants/assigned"
 
 generate () {
 
@@ -64,31 +72,18 @@ Chakotay -Janeway
 T'Pol
 O'Brien
 Worf =Picard
-"La Forge"
+LaForge
 eof
     
-}
-
-get_participants () {
-
-    grep -Po '^[^ ]+' < "$input"
-    
-}
-
-get_fixes () {
-    :
-}
-
-get_exclusions () {
-    grep 
 }
 
 checks () {
 
     fail=0
+    fail_report="$fails"
 
-    num_assignments="$(cat "$participants"/*."$assignments" | wc -l)"
-    num_uniq_ass="$(cat "$participants"/*."$assignments" | sort -u | wc -l)"
+    num_assignments="$(cat "$run"/*."$assignments" | wc -l)"
+    num_uniq_ass="$(cat "$run"/*."$assignments" | sort -u | wc -l)"
 
     if [ $num_assignments -eq $num_uniq_ass ]; then
         info "uniq test pass"
@@ -96,24 +91,34 @@ checks () {
         fail=$((fail+1))
     fi
 
-    matchtest1=$(mktemp)
-    matchtest2=$(mktemp)
-    cat "$participants"/*."$assignments" | sort -u > $matchtest1
-    cat "$assigned" | sort -u > $matchtest2
+    # matchtest1=$(mktemp)
+    # matchtest2=$(mktemp)
+    # cat "$participants"/*."$assignments" > $matchtest1
+    # cat "$assigned" | sort -u > $matchtest2
+    # diff $matchtest1 $matchtest2 || fail=$((fail + 1))
 
-    diff $matchtest1 $matchtest2 || fail=$((fail + 1))
+    cat "$all" | while read -r p; do
+        num_times_assigned="$(cat "$run"/*."$assigned" | grep -F "$p" | wc -l)"
 
-    for p in "$all"; do
-        recMatchesAgg="$( grep -F "$line" < "$assigned" | wc -l)"
-        recMatchesFiles="$( cat "$participants"/*."$assigned" | grep -F "$line" | wc -l )"
-             
-        return $fail
+        fail=$((fail+1))
+    done
+    
+    recMatchesAgg="$( grep -F "$line" < "$assigned" | wc -l)"
+    recMatchesFiles="$( cat "$run"/*."$assigned" | grep -F "$line" | wc -l )"
+
+    if [ $recMatchesAgg -ne 1 ] || [ $recMatchesFiles -ne 1 ]; then
+        errortext "$line matches $recMatchesAgg or $recMatchesFiles"
+        fail=$((fail+1))
+    fi
+    done
+    
+    return $fail
 }
 
 make_matches () {
 
     cat "$all" | while read -r line; do
-        p="$participants/$line"
+        p="$run/$line"
 
         shuf "$p.candidates" \
             | grep -vFf "$assigned" \
@@ -132,27 +137,36 @@ run_tests () {
     make_matches || die
 
     checks
-        
+    
 }
 
-setup_candidates () {
-
-    touch "$assigned" || die
-
-    cat "$all" | while read -r part; do
-
-        cat "$all" \
-            | grep -vF "$part" \
-            | grep -vFf "$participants/$part.$exclusions" \
-            | grep -vFf "$assigned" \
-                   >> "$participants/$part.$candidates"
-    done
+candidates_for () {
+    [ $# -eq 1 ] || die
+    
+    cat "$all" \
+        | grep -vF "$1" \
+        | grep -vFf "$1.$exclusions" \
+        | grep -vFf <( cat "$run"/*."$assignments" )
 }
+
+# setup_candidates () {
+
+#     touch "$assigned" || die
+
+#     cat "$all" | while read -r part; do
+
+#         cat "$all" \
+    #             | grep -vF "$part" \
+    #             | grep -vFf "$participants/$part.$exclusions" \
+    #             | grep -vFf "$assigned" \
+    #                    >> "$participants/$part.$candidates"
+#     done
+# }
 
 assign () {
     [ $# -eq 2 ] || die
 
-    assfile="$participants/$1.$assignments"
+    assfile="$run/$1.$assignments"
 
     if [ $(wc -c < "$assfile") -gt 0 ]; then
         warn "$1 is already assigned to $( <"$assfile" ), adding $2"
@@ -165,20 +179,21 @@ assign () {
 setup_data () {
     #  get_participants > $participants
 
-    mkdir $participants || die
+    mkdir $run || die
 
     while read -r linestring; do
+        readarray -r line <<< "$linestring"
         line=($linestring)
 
         [ ${#line} -gt 0 ] && this_part="${line[0]}" && echo "$this_part" >> "$all"
 
-        touch "$participants/$this_part.assignments" "$participants/$this_part.$exclusions" "$participants/$this_part.$candidates"
+        touch "$run/$this_part.assignments" "$run/$this_part.$exclusions" "$run/$this_part.$candidates"
         
         for item in "${line[@]}"; do
             if [[ $item =~ -(.*)$ ]]; then
-                echo "${BASH_REMATCH[1]}" >> "$participants/$this_part.$exclusions"
+                echo "${BASH_REMATCH[1]}" >> "$run/$this_part.$exclusions"
             elif [[ $item =~ =(.*)$ ]]; then
-                echo "${BASH_REMATCH[1]}" >> "$participants/$this_part.$assignments"
+                echo "${BASH_REMATCH[1]}" >> "$run/$this_part.$assignments"
             else            
                 [[ "$item" != "$this_part" ]] && warn "Incorrect specification for $this_part: not sure what to do with $item"
             fi
@@ -186,32 +201,43 @@ setup_data () {
     done
 }
 
-    if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
-        checks || die
+if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
 
-        [ -n "$arg_input_file" ] \
-            && info "using input file $arg_input_file" \
-            && "$0" < "$arg_input_file" \
-            && exit $?
-        
-        [ -n "$arg_generate_file" ] \
-            && "$0" -g > "$participants" \
-            && exit $?
+    [ -n "$arg_input_file" ] \
+        && info "using input file $arg_input_file" \
+        && "$0" < "$arg_input_file" \
+        && exit $?
+    
+    [ -n "$arg_generate_file" ] \
+        && "$0" -g > "$participants" \
+        && exit $?
 
-        [ -n "$arg_generate_stdout" ] \
-            && generate \
-            && exit $?
+    [ -n "$arg_generate_stdout" ] \
+        && generate \
+        && exit $?
 
-        [ -n "$arg_tests" ] && run_tests && exit $?
+    [ -n "$arg_tests" ] && run_tests && exit $?
 
-        cat - | setup_data && setup_candidates || die
+    cat - | setup_data && setup_candidates || die
 
-        make_matches || die
+    make_matches || die
 
-        checks
+    for i in {1..100}; do
+        if checks; then
+            cd "$run"
+            for d in *.assigned; do
+                printf '%-15s: %s' "$d" $(cat "$d")
+            done
+            exit 0
+        else
+            thinbanner next run
+            set_run_id
+            make_matches || die
+        fi
+    done
 
 
-    else
-        echo "Happy debugging!"
-    fi
+else
+    echo "Happy debugging!"
+fi
 
